name: mbpsrl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy=1.16.5
  - scipy=1.3.3
  - pandas=1.1.2
  - matplotlib=3.3.2
  - pillow=7.2.0
  - pip:
    - -r pip-requirements.txt
